-- phpMyAdmin SQL Dump
-- version 4.8.5
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Sep 12, 2021 at 05:23 PM
-- Server version: 5.7.26
-- PHP Version: 7.2.18

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `zigmacimdb`
--

-- --------------------------------------------------------

--
-- Table structure for table `movie_data`
--

DROP TABLE IF EXISTS `movie_data`;
CREATE TABLE IF NOT EXISTS `movie_data` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'primary key',
  `imdb_id` varchar(10) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `local_title` text,
  `runtime` varchar(20) DEFAULT NULL,
  `date_published` varchar(50) DEFAULT NULL,
  `genre` text,
  `img_url` text,
  `img_path` text,
  `summary` text,
  `actors` text,
  `rating` float DEFAULT NULL,
  `local_path` text,
  `created_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'created time',
  `updated_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated time',
  `type` varchar(30) DEFAULT NULL COMMENT 'Movie or TV',
  `country` varchar(100) DEFAULT NULL,
  `imdb_fetch` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `imdb_id` (`imdb_id`),
  UNIQUE KEY `imdb_id_2` (`imdb_id`),
  UNIQUE KEY `imdb_id_3` (`imdb_id`),
  UNIQUE KEY `imdb_id_4` (`imdb_id`)
) ENGINE=MyISAM AUTO_INCREMENT=231 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `movie_data`
--

INSERT INTO `movie_data` (`id`, `imdb_id`, `title`, `local_title`, `runtime`, `date_published`, `genre`, `img_url`, `img_path`, `summary`, `actors`, `rating`, `local_path`, `created_time`, `updated_time`, `type`, `country`, `imdb_fetch`) VALUES
(166, 'tt7131622', 'Once Upon a Time... In Hollywood', NULL, '161 min', '2019-07-26', 'Comedy, Drama', 'https://m.media-amazon.com/images/M/MV5BOTg4ZTNkZmUtMzNlZi00YmFjLTk1MmUtNWQwNTM0YjcyNTNkXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_SX300.jpg', 'tt7131622.jpg', 'A faded television actor and his stunt double strive to achieve fame and success in the final years of Hollywood\'s Golden Age in 1969 Los Angeles.', 'Leonardo DiCaprio, Brad Pitt, Margot Robbie, Emile Hirsch', 7.6, NULL, '2021-03-04 13:43:33', '2021-09-10 06:35:54', 'movie', NULL, 1),
(165, 'tt0478970', 'Ant-Man', NULL, '117 min', '2015-07-17', 'Action, Adventure, Comedy, Sci-Fi', 'https://m.media-amazon.com/images/M/MV5BMjM2NTQ5Mzc2M15BMl5BanBnXkFtZTgwNTcxMDI2NTE@._V1_SX300.jpg', 'tt0478970.jpg', 'Armed with the astonishing ability to shrink in scale but increase in strength, con-man Scott Lang must embrace his inner-hero and help his mentor, Dr. Hank Pym, protect the secret behind his spectacular Ant-Man suit from a new generation of towering threats. Against seemingly insurmountable obstacles, Pym and Lang must plan and pull off a heist that will save the world.', 'Paul Rudd, Michael Douglas, Evangeline Lilly, Corey Stoll', 7.3, NULL, '2021-03-04 13:43:33', '2021-09-10 06:35:58', 'movie', NULL, 1),
(163, 'tt4154796', 'Avengers: Endgame', NULL, '181 min', '2019-04-26', 'Action, Adventure, Drama, Sci-Fi', 'https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SX300.jpg', 'tt4154796.jpg', 'After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos\' actions and restore balance to the universe.', 'Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth', 8.4, NULL, '2021-03-04 13:43:32', '2021-09-10 06:36:01', 'movie', NULL, 1),
(164, 'tt0451279', 'Wonder Woman', NULL, '141 min', '2017-06-02', 'Action, Adventure, Fantasy, Sci-Fi, War', 'https://m.media-amazon.com/images/M/MV5BMTYzODQzYjQtNTczNC00MzZhLTg1ZWYtZDUxYmQ3ZTY4NzA1XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg', 'tt0451279.jpg', 'Diana, princess of the Amazons, trained to be an unconquerable warrior. Raised on a sheltered island paradise, when a pilot crashes on their shores and tells of a massive conflict raging in the outside world, Diana leaves her home, convinced she can stop the threat. Fighting alongside man in a war to end all wars, Diana will discover her full powers and her true destiny.', 'Gal Gadot, Chris Pine, Connie Nielsen, Robin Wright', 7.4, NULL, '2021-03-04 13:43:32', '2021-09-10 06:36:03', 'movie', NULL, 1),
(167, 'tt0111161', 'The Shawshank Redemption', NULL, '142 min', '1994-10-14', 'Drama', 'https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'tt0111161.jpg', 'Chronicles the experiences of a formerly successful banker as a prisoner in the gloomy jailhouse of Shawshank after being found guilty of a crime he did not commit. The film portrays the man\'s unique way of dealing with his new, torturous life; along the way he befriends a number of fellow prisoners, most notably a wise long-term inmate named Red.', 'Tim Robbins, Morgan Freeman, Bob Gunton', 9.3, NULL, '2021-07-29 14:17:19', '2021-09-10 06:36:07', 'movie', NULL, 1),
(168, 'tt0068646', 'The Godfather', NULL, '175 min', '1972-03-24', 'Crime, Drama', 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'tt0068646.jpg', 'The Godfather \"Don\" Vito Corleone is the head of the Corleone mafia family in New York. He is at the event of his daughter\'s wedding. Michael, Vito\'s youngest son and a decorated WW II Marine is also present at the wedding. Michael seems to be uninterested in being a part of the family business. Vito is a powerful man, and is kind to all those who give him respect but is ruthless against those who do not. But when a powerful and treacherous rival wants to sell drugs and needs the Don\'s influence for the same, Vito refuses to do it. What follows is a clash between Vito\'s fading old values and the new ways which may cause Michael to do the thing he was most reluctant in doing and wage a mob war against all the other mafia families which could tear the Corleone family apart.', 'Marlon Brando, Al Pacino, James Caan', 9.2, NULL, '2021-07-29 14:17:20', '2021-09-10 06:36:10', 'movie', NULL, 1),
(169, 'tt0071562', 'The Godfather: Part II', NULL, '202 min', '1974-12-18', 'Crime, Drama', 'https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'tt0071562.jpg', 'The continuing saga of the Corleone crime family tells the story of a young Vito Corleone growing up in Sicily and in 1910s New York; and follows Michael Corleone in the 1950s as he attempts to expand the family business into Las Vegas, Hollywood and Cuba.', 'Al Pacino, Robert De Niro, Robert Duvall', 9, NULL, '2021-07-29 14:20:08', '2021-09-10 06:36:13', 'movie', NULL, 1),
(170, 'tt0468569', 'The Dark Knight', NULL, '152 min', '2008-07-18', 'Action, Crime, Drama', 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg', 'tt0468569.jpg', 'Set within a year after the events of Batman Begins (2005), Batman, Lieutenant James Gordon, and new District Attorney Harvey Dent successfully begin to round up the criminals that plague Gotham City, until a mysterious and sadistic criminal mastermind known only as \"The Joker\" appears in Gotham, creating a new wave of chaos. Batman\'s struggle against The Joker becomes deeply personal, forcing him to \"confront everything he believes\" and improve his technology to stop him. A love triangle develops between Bruce Wayne, Dent, and Rachel Dawes.', 'Christian Bale, Heath Ledger, Aaron Eckhart', 9, NULL, '2021-07-29 14:20:10', '2021-09-10 06:36:15', 'movie', NULL, 1),
(171, 'tt0050083', '12 Angry Men', NULL, '96 min', '1957-04-10', 'Crime, Drama', 'https://m.media-amazon.com/images/M/MV5BMWU4N2FjNzYtNTVkNC00NzQ0LTg0MjAtYTJlMjFhNGUxZDFmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg', 'tt0050083.jpg', 'The defense and the prosecution have rested, and the jury is filing into the jury room to decide if a young man is guilty or innocent of murdering his father. What begins as an open-and-shut case of murder soon becomes a detective story that presents a succession of clues creating doubt, and a mini-drama of each of the jurors\' prejudices and preconceptions about the trial, the accused, AND each other. Based on the play, all of the action takes place on the stage of the jury room.', 'Henry Fonda, Lee J. Cobb, Martin Balsam', 9, NULL, '2021-07-29 14:20:11', '2021-09-10 06:36:18', 'movie', NULL, 1),
(172, 'tt0108052', 'Schindler\'s List', NULL, '195 min', '1994-02-04', 'Biography, Drama, History', 'https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'tt0108052.jpg', 'Oskar Schindler is a vain and greedy German businessman who becomes an unlikely humanitarian amid the barbaric German Nazi reign when he feels compelled to turn his factory into a refuge for Jews. Based on the true story of Oskar Schindler who managed to save about 1100 Jews from being gassed at the Auschwitz concentration camp, it is a testament to the good in all of us.', 'Liam Neeson, Ralph Fiennes, Ben Kingsley', 8.9, NULL, '2021-07-29 14:20:13', '2021-09-10 06:36:20', 'movie', NULL, 1),
(173, 'tt0110912', 'Pulp Fiction', NULL, '154 min', '1994-10-14', 'Crime, Drama', 'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'tt0110912.jpg', 'Jules Winnfield (Samuel L. Jackson) and Vincent Vega (John Travolta) are two hit men who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace (Ving Rhames). Wallace has also asked Vincent to take his wife Mia (Uma Thurman) out a few days later when Wallace himself will be out of town. Butch Coolidge (Bruce Willis) is an aging boxer who is paid by Wallace to lose his fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.', 'John Travolta, Uma Thurman, Samuel L. Jackson', 8.9, NULL, '2021-07-29 14:20:14', '2021-09-10 06:36:23', 'movie', NULL, 1),
(174, 'tt0060196', 'Il buono, il brutto, il cattivo', NULL, '178 min', '1967-12-29', 'Western', 'https://m.media-amazon.com/images/M/MV5BOTQ5NDI3MTI4MF5BMl5BanBnXkFtZTgwNDQ4ODE5MDE@._V1_SX300.jpg', 'tt0060196.jpg', 'Blondie (The Good) (Clint Eastwood) is a professional gunslinger who is out trying to earn a few dollars. Angel Eyes (The Bad) (Lee Van Cleef) is a hitman who always commits to a task and sees it through, as long as he is paid to do so. And Tuco (The Ugly) (Eli Wallach) is a wanted outlaw trying to take care of his own hide. Tuco and Blondie share a partnership together making money off of Tuco\'s bounty, but when Blondie unties the partnership, Tuco tries to hunt down Blondie. When Blondie and Tuco come across a horse carriage loaded with dead bodies, they soon learn from the only survivor, Bill Carson (Antonio Casale), that he and a few other men have buried a stash of gold in a cemetery. Unfortunately, Carson dies and Tuco only finds out the name of the cemetery, while Blondie finds out the name on the grave. Now the two must keep each other alive in order to find the gold. Angel Eyes (who had been looking for Bill Carson) discovers that Tuco and Blondie met with Carson and knows they know the location of the gold. All he needs is for the two to lead him to it. Now The Good, the Bad and the Ugly must all battle it out to get their hands on two hundred thousand dollars worth of gold.', 'Clint Eastwood, Eli Wallach, Lee Van Cleef', 8.8, NULL, '2021-07-29 14:20:16', '2021-09-10 06:36:27', 'movie', NULL, 1),
(175, 'tt0167260', 'The Lord of the Rings: The Return of the King', NULL, '201 min', '2003-12-17', 'Action, Adventure, Drama', 'https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'tt0167260.jpg', 'The final confrontation between the forces of good and evil fighting for control of the future of Middle-earth. Frodo and Sam reach Mordor in their quest to destroy the One Ring, while Aragorn leads the forces of good against Sauron\'s evil army at the stone city of Minas Tirith.', 'Elijah Wood, Viggo Mortensen, Ian McKellen', 8.9, NULL, '2021-07-29 14:20:17', '2021-09-10 06:35:26', 'movie', NULL, 1),
(176, 'tt0137523', 'Fight Club', NULL, '139 min', '1999-10-15', 'Drama', 'https://m.media-amazon.com/images/M/MV5BMmEzNTkxYjQtZTc0MC00YTVjLTg5ZTEtZWMwOWVlYzY0NWIwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'tt0137523.jpg', 'A nameless first person narrator (Edward Norton) attends support groups in attempt to subdue his emotional state and relieve his insomniac state. When he meets Marla (Helena Bonham Carter), another fake attendee of support groups, his life seems to become a little more bearable. However when he associates himself with Tyler (Brad Pitt) he is dragged into an underground fight club and soap making scheme. Together the two men spiral out of control and engage in competitive rivalry for love and power.', 'Brad Pitt, Edward Norton, Meat Loaf', 8.8, NULL, '2021-07-29 14:20:19', '2021-09-10 06:35:30', 'movie', NULL, 1),
(177, 'tt0120737', 'The Lord of the Rings: The Fellowship of the Ring', NULL, '178 min', '2001-12-19', 'Action, Adventure, Drama', 'https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg', 'tt0120737.jpg', 'An ancient Ring thought lost for centuries has been found, and through a strange twist of fate has been given to a small Hobbit named Frodo. When Gandalf discovers the Ring is in fact the One Ring of the Dark Lord Sauron, Frodo must make an epic quest to the Cracks of Doom in order to destroy it. However, he does not go alone. He is joined by Gandalf, Legolas the elf, Gimli the Dwarf, Aragorn, Boromir, and his three Hobbit friends Merry, Pippin, and Samwise. Through mountains, snow, darkness, forests, rivers and plains, facing evil and danger at every corner the Fellowship of the Ring must go. Their quest to destroy the One Ring is the only hope for the end of the Dark Lords reign.', 'Elijah Wood, Ian McKellen, Orlando Bloom', 8.8, NULL, '2021-07-29 14:21:53', '2021-09-10 06:35:33', 'movie', NULL, 1),
(178, 'tt0080684', 'Star Wars: Episode V - The Empire Strikes Back', NULL, '124 min', '1980-06-20', 'Action, Adventure, Fantasy', 'https://m.media-amazon.com/images/M/MV5BYmU1NDRjNDgtMzhiMi00NjZmLTg5NGItZDNiZjU5NTU4OTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'tt0080684.jpg', 'Luke Skywalker, Han Solo, Princess Leia and Chewbacca face attack by the Imperial forces and its AT-AT walkers on the ice planet Hoth. While Han and Leia escape in the Millennium Falcon, Luke travels to Dagobah in search of Yoda. Only with the Jedi Master\'s help will Luke survive when the Dark Side of the Force beckons him into the ultimate duel with Darth Vader.', 'Mark Hamill, Harrison Ford, Carrie Fisher', 8.7, NULL, '2021-07-29 14:21:55', '2021-09-10 06:35:36', 'movie', NULL, 1),
(179, 'tt0109830', 'Forrest Gump', NULL, '142 min', '1994-07-06', 'Drama, Romance', 'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'tt0109830.jpg', 'Forrest Gump is a simple man with a low I.Q. but good intentions. He is running through childhood with his best and only friend Jenny. His \'mama\' teaches him the ways of life and leaves him to choose his destiny. Forrest joins the army for service in Vietnam, finding new friends called Dan and Bubba, he wins medals, creates a famous shrimp fishing fleet, inspires people to jog, starts a ping-pong craze, creates the smiley, writes bumper stickers and songs, donates to people and meets the president several times. However, this is all irrelevant to Forrest who can only think of his childhood sweetheart Jenny Curran, who has messed up her life. Although in the end all he wants to prove is that anyone can love anyone.', 'Tom Hanks, Robin Wright, Gary Sinise', 8.8, NULL, '2021-07-29 14:21:56', '2021-09-10 06:35:38', 'movie', NULL, 1),
(180, 'tt1375666', 'Inception', NULL, '148 min', '2010-07-16', 'Action, Adventure, Sci-Fi', 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg', 'tt1375666.jpg', 'Dom Cobb is a skilled thief, the absolute best in the dangerous art of extraction, stealing valuable secrets from deep within the subconscious during the dream state, when the mind is at its most vulnerable. Cobb\'s rare ability has made him a coveted player in this treacherous new world of corporate espionage, but it has also made him an international fugitive and cost him everything he has ever loved. Now Cobb is being offered a chance at redemption. One last job could give him his life back but only if he can accomplish the impossible, inception. Instead of the perfect heist, Cobb and his team of specialists have to pull off the reverse: their task is not to steal an idea, but to plant one. If they succeed, it could be the perfect crime. But no amount of careful planning or expertise can prepare the team for the dangerous enemy that seems to predict their every move. An enemy that only Cobb could have seen coming.', 'Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page', 8.8, NULL, '2021-07-29 14:21:57', '2021-09-10 06:36:29', 'movie', NULL, 1),
(181, 'tt0073486', 'One Flew Over the Cuckoo\'s Nest', NULL, '133 min', '1975-11-19', 'Drama', 'https://m.media-amazon.com/images/M/MV5BZjA0OWVhOTAtYWQxNi00YzNhLWI4ZjYtNjFjZTEyYjJlNDVlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'tt0073486.jpg', 'McMurphy has a criminal past and has once again gotten himself into trouble and is sentenced by the court. To escape labor duties in prison, McMurphy pleads insanity and is sent to a ward for the mentally unstable. Once here, McMurphy both endures and stands witness to the abuse and degradation of the oppressive Nurse Ratched, who gains superiority and power through the flaws of the other inmates. McMurphy and the other inmates band together to make a rebellious stance against the atrocious Nurse.', 'Jack Nicholson, Louise Fletcher, Michael Berryman', 8.7, NULL, '2021-07-29 14:21:58', '2021-09-10 06:36:31', 'movie', NULL, 1),
(182, 'tt0167261', 'The Lord of the Rings: The Two Towers', NULL, '179 min', '2002-12-18', 'Action, Adventure, Drama', 'https://m.media-amazon.com/images/M/MV5BZGMxZTdjZmYtMmE2Ni00ZTdkLWI5NTgtNjlmMjBiNzU2MmI5XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'tt0167261.jpg', 'The continuing quest of Frodo and the Fellowship to destroy the One Ring. Frodo and Sam discover they are being followed by the mysterious Gollum. Aragorn, the Elf archer Legolas, and Gimli the Dwarf encounter the besieged Rohan kingdom, whose once great King Theoden has fallen under Saruman\'s deadly spell.', 'Elijah Wood, Ian McKellen, Viggo Mortensen', 8.7, NULL, '2021-07-29 14:22:00', '2021-09-10 06:36:33', 'movie', NULL, 1),
(183, 'tt0099685', 'Goodfellas', NULL, '146 min', '1990-09-21', 'Biography, Crime, Drama', 'https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'tt0099685.jpg', 'Henry Hill might be a small time gangster, who may have taken part in a robbery with Jimmy Conway and Tommy De Vito, two other gangsters who might have set their sights a bit higher. His two partners could kill off everyone else involved in the robbery, and slowly start to think about climbing up through the hierarchy of the Mob. Henry, however, might be badly affected by his partners\' success, but will he consider stooping low enough to bring about the downfall of Jimmy and Tommy?', 'Robert De Niro, Ray Liotta, Joe Pesci', 8.7, NULL, '2021-07-29 14:22:01', '2021-09-10 06:36:37', 'movie', NULL, 1),
(184, 'tt0133093', 'The Matrix', NULL, '136 min', '1999-03-31', 'Action, Sci-Fi', 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'tt0133093.jpg', 'Thomas A. Anderson is a man living two lives. By day he is an average computer programmer and by night a hacker known as Neo. Neo has always questioned his reality, but the truth is far beyond his imagination. Neo finds himself targeted by the police when he is contacted by Morpheus, a legendary computer hacker branded a terrorist by the government. As a rebel against the machines, Neo must confront the agents: super-powerful computer programs devoted to stopping Neo and the entire human rebellion.', 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss', 8.7, NULL, '2021-07-29 14:22:02', '2021-09-10 06:36:39', 'movie', NULL, 1),
(185, 'tt0076759', 'Star Wars', NULL, '121 min', '1977-05-25', 'Action, Adventure, Fantasy', 'https://m.media-amazon.com/images/M/MV5BNzVlY2MwMjktM2E4OS00Y2Y3LWE3ZjctYzhkZGM3YzA1ZWM2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'tt0076759.jpg', 'The Imperial Forces, under orders from cruel Darth Vader, hold Princess Leia hostage in their efforts to quell the rebellion against the Galactic Empire. Luke Skywalker and Han Solo, captain of the Millennium Falcon, work together with the companionable droid duo R2-D2 and C-3PO to rescue the beautiful princess, help the Rebel Alliance and restore freedom and justice to the Galaxy.', 'Mark Hamill, Harrison Ford, Carrie Fisher', 8.6, NULL, '2021-07-29 14:22:04', '2021-09-10 06:36:42', 'movie', NULL, 1),
(186, 'tt0047478', 'Shichinin no samurai', NULL, '207 min', '1956-11-19', 'Action, Adventure, Drama', 'https://m.media-amazon.com/images/M/MV5BOWE4ZDdhNmMtNzE5ZC00NzExLTlhNGMtY2ZhYjYzODEzODA1XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg', 'tt0047478.jpg', 'A veteran samurai, who has fallen on hard times, answers a village\'s request for protection from bandits. He gathers 6 other samurai to help him, and they teach the townspeople how to defend themselves, and they supply the samurai with three small meals a day. The film culminates in a giant battle when 40 bandits attack the village.', 'Toshirô Mifune, Takashi Shimura, Keiko Tsushima', 8.6, NULL, '2021-07-29 14:22:05', '2021-09-10 06:36:46', 'movie', NULL, 1),
(187, 'tt0795176', 'Planet Earth', NULL, '538 min', '2007-03-25', 'Documentary', 'https://m.media-amazon.com/images/M/MV5BNmZlYzIzMTItY2EzYS00YTEyLTg0ZjEtMDMzZjM3ODdhN2UzXkEyXkFqcGdeQXVyNjI0MDg2NzE@._V1_SX300.jpg', 'tt0795176.jpg', 'Each 50 minute episode features a global overview of a different biome or habitat on Earth (Polar, Mountain, Cave, Desert, Plains, Fresh Water, Seas, Ocean, Forest), followed by a ten-minute featurette which takes a behind-the-scenes look at the challenges of filming the episode.', 'David Attenborough, Sigourney Weaver, Thomas Anguti Johnston', 9.4, NULL, '2021-07-29 16:23:15', '2021-09-10 06:36:48', 'series', NULL, 1),
(188, 'tt5491994', 'Planet Earth II', NULL, '298 min', '2017-02-18', 'Documentary', 'https://m.media-amazon.com/images/M/MV5BZWYxODViMGYtMGE2ZC00ZGQ3LThhMWUtYTVkNGE3OWU4NWRkL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMjYwNDA2MDE@._V1_SX300.jpg', 'tt5491994.jpg', 'Wildlife documentary series with David Attenborough, beginning with a look at the remote islands which offer sanctuary to some of the planet\'s rarest creatures, to the beauty of cities, which are home to humans, and animals..', 'David Attenborough', 9.5, NULL, '2021-07-29 16:23:54', '2021-09-10 06:36:51', 'series', NULL, 1),
(189, 'tt0185906', 'Band of Brothers', NULL, '594 min', '2001-09-09', 'Action, Drama, History', 'https://m.media-amazon.com/images/M/MV5BMTI3ODc2ODc0M15BMl5BanBnXkFtZTYwMjgzNjc3._V1_SX300.jpg', 'tt0185906.jpg', 'This is the story of \"E\" Easy Company, 506th Regiment of the 101st Airborne Division from their initial training starting in 1942 to the end of World War II. They parachuted behind enemy lines in the early hours of D-Day in support of the landings at Utah beach, participated in the liberation of Carentan and again parachuted into action during Operation Market Garden. They also liberated a concentration camp and were the first to enter Hitler\'s mountain retreat in Berchtesgaden. A fascinating tale of comradeship that is, in the end, a tale of ordinary men who did extraordinary things.', 'Scott Grimes, Damian Lewis, Ron Livingston', 9.4, NULL, '2021-07-29 16:24:10', '2021-09-10 06:36:54', 'series', NULL, 1),
(190, 'tt0903747', 'Breaking Bad', NULL, '49 min', '2008-01-20', 'Crime, Drama, Thriller', 'https://m.media-amazon.com/images/M/MV5BMjhiMzgxZTctNDc1Ni00OTIxLTlhMTYtZTA3ZWFkODRkNmE2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'tt0903747.jpg', 'When chemistry teacher Walter White is diagnosed with Stage III cancer and given only two years to live, he decides he has nothing to lose. He lives with his teenage son, who has cerebral palsy, and his wife, in New Mexico. Determined to ensure that his family will have a secure future, Walt embarks on a career of drugs and crime. He proves to be remarkably proficient in this new world as he begins manufacturing and selling methamphetamine with one of his former students. The series tracks the impacts of a fatal diagnosis on a regular, hard working man, and explores how a fatal diagnosis affects his morality and transforms him into a major player of the drug trade.', 'Bryan Cranston, Aaron Paul, Anna Gunn', 9.4, NULL, '2021-07-29 16:24:42', '2021-09-10 06:36:56', 'series', NULL, 1),
(191, 'tt10648714', 'Chernobyl', NULL, '136 min', '2021-04-15', 'Comedy, Drama, History', 'https://m.media-amazon.com/images/M/MV5BZmVmNjZjODktNTMxMC00ZjA4LThlZmItN2Q5MjQzMGM1OTI4XkEyXkFqcGdeQXVyMjUwNjY5MzA@._V1_SX300.jpg', 'tt10648714.jpg', 'Chernobyl: The Abyss is the first major Russian feature film about the aftermath of the explosion at the Chernobyl nuclear power station, when hundreds of people sacrificed their lives to clean up the site of the catastrophe, and to successfully prevent an even bigger disaster that could have turned a large part of the European continent into an uninhabitable exclusion zone. The unlikely hero of the film is Alexey, a fireman at the power station. He is accompanied by Valery, an engineer, and Boris, a military diver, on a perilous mission to drain water from a reservoir under the burning reactor. They have no time for proper planning; water in the flooded corridors they will have to traverse is getting hotter by the hour as the molten reactor core seeps ever closer. Prepared to sacrifice their own lives in order to prevent an even greater catastrophe, the three men descend into the depths of the reactor building.', 'Danila Kozlovskiy, Oksana Akinshina, Filipp Avdeev', 4.3, NULL, '2021-07-29 16:25:04', '2021-09-10 06:36:58', 'movie', NULL, 1),
(192, 'tt0306414', 'The Wire', NULL, '59 min', '2002-06-02', 'Crime, Drama, Thriller', 'https://m.media-amazon.com/images/M/MV5BNTllYzFhMjAtZjExNS00MjM4LWE5YmMtOGFiZGRlOTU5YzJiXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_SX300.jpg', 'tt0306414.jpg', 'Set in Baltimore, this show centers around the city\'s inner-city drug scene. It starts as mid-level drug dealer, D\'Angelo Barksdale beats a murder rap. After a conversation with a judge, Det. James McNulty has been assigned to lead a joint homicide and narcotics team, in order to bring down drug kingpin Avon Barksdale. Avon Barksdale, accompanied by his right-hand man Stringer Bell, enforcer Wee-Bey and many lieutenants (including his own nephew, D\'Angelo Barksdale), has to deal with law enforcement, informants in his own camp, and competition with a local rival, Omar, who\'s been robbing Barksdale\'s dealers and reselling the drugs. The supervisor of the investigation, Lt. Cedric Daniels, has to deal with his own problems, such as a corrupt bureaucracy, some of his detectives beating suspects, hard-headed but determined Det. McNulty, and a blackmailing deputy. The show depicts the lives of every part of the drug \"food chain\", from junkies to dealers, and from cops to politicians.', 'Dominic West, Lance Reddick, Sonja Sohn', 9.3, NULL, '2021-07-29 16:25:16', '2021-09-10 06:37:01', 'series', NULL, 1),
(193, 'tt6769208', 'Blue Planet II', NULL, '364 min', '2018-01-20', 'Documentary', 'https://m.media-amazon.com/images/M/MV5BYjg2ODk0MjUtNmMzZS00MjY0LWI1YWMtN2JhMjRmZGUwY2I3XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'tt6769208.jpg', 'Nearly a generation after the acclaimed Blue Planet documentary was released, David Attenborough returns to narrate this groundbreaking sequel/reboot. Blue Planet ll focuses more heavily on mankind\'s influence on the world\'s oceans through both global pollution and climate change. This series features a variety of revolutionary segments never before seen in a video documentary, including: cuttlefish that hypnotize crabs to stun them, giant trevally that leap out of the water to catch low flying birds, and newly discovered dancing yeti crabs.', 'David Attenborough, Peter Drost, Roger Horrocks', 9.3, NULL, '2021-07-29 16:25:28', '2021-09-10 06:37:03', 'series', NULL, 1),
(194, 'tt9253866', 'Our Planet', NULL, '403 min', '2019-04-05', 'Documentary', 'https://m.media-amazon.com/images/M/MV5BN2I1ZjA5YjQtYmQ0ZS00ZmE1LTk1ZjktNTQ5ODIzY2JiZDdhXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_SX300.jpg', 'tt9253866.jpg', 'Documentary series focusing on the breadth of the diversity of habitats around the world, from the remote Arctic wilderness and mysterious deep oceans to the vast landscapes of Africa and diverse jungles of South America.', 'David Attenborough', 9.3, NULL, '2021-07-29 16:25:40', '2021-09-10 06:37:05', 'series', NULL, 1),
(195, 'tt2395695', 'Cosmos: A Spacetime Odyssey', NULL, '557 min', '2014-03-09', 'Documentary', 'https://m.media-amazon.com/images/M/MV5BZTk5OTQyZjYtMDk3Yy00YjhmLWE2MTYtZmY4NTg1YWUzZTQ0XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg', 'tt2395695.jpg', 'Join the heroic quest for knowledge as we set course for the stars with the twenty-first century reboot of Cosmos. Hosted by world-renowned astrophysicist Neil deGrasse Tyson, this thirteen-part ground-breaking series will venture to new worlds, trace our roots back to the hearts of ancient stars, and travel across the universe for a vision of the cosmos on the grandest scale.', 'Neil deGrasse Tyson, Stoney Emshwiller, Piotr Michael', 9.3, NULL, '2021-07-29 16:25:57', '2021-09-10 06:37:07', 'series', NULL, 1),
(196, 'tt0417299', 'Avatar: The Last Airbender', NULL, '23 min', '2005-02-21', 'Animation, Action, Adventure', 'https://m.media-amazon.com/images/M/MV5BODc5YTBhMTItMjhkNi00ZTIxLWI0YjAtNTZmOTY0YjRlZGQ0XkEyXkFqcGdeQXVyODUwNjEzMzg@._V1_SX300.jpg', 'tt0417299.jpg', 'The world is divided into four elemental nations: The Northern and Southern Water Tribes, the Earth Kingdom, the Fire Nation, and the Air Nomads. The Avatar upholds the balance between the nations, but everything changed when the Fire Nation invaded. Only the Avatar, master of all four elements, can stop them. But when the world needs him most, he vanishes. A hundred years later Katara and Sokka discover the new Avatar, an airbender named Aang. Together they must help Aang master the elements and save the world.', 'Dee Bradley Baker, Zach Tyler, Mae Whitman', 9.3, NULL, '2021-07-29 16:26:36', '2021-09-10 06:37:09', 'series', NULL, 1),
(197, 'tt0944947', 'Game of Thrones', NULL, '57 min', '2011-04-17', 'Action, Adventure, Drama', 'https://m.media-amazon.com/images/M/MV5BYTRiNDQwYzAtMzVlZS00NTI5LWJjYjUtMzkwNTUzMWMxZTllXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_SX300.jpg', 'tt0944947.jpg', 'In the mythical continent of Westeros, several powerful families fight for control of the Seven Kingdoms. As conflict erupts in the kingdoms of men, an ancient enemy rises once again to threaten them all. Meanwhile, the last heirs of a recently usurped dynasty plot to take back their homeland from across the Narrow Sea.', 'Emilia Clarke, Peter Dinklage, Kit Harington', 9.3, NULL, '2021-07-29 16:27:13', '2021-09-10 06:37:11', 'series', NULL, 1),
(198, 'tt0141842', 'The Sopranos', NULL, '55 min', '1999-01-10', 'Crime, Drama', 'https://m.media-amazon.com/images/M/MV5BZGJjYzhjYTYtMDBjYy00OWU1LTg5OTYtNmYwOTZmZjE3ZDdhXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg', 'tt0141842.jpg', 'An innovative look at the life of fictional Mafia Capo Tony Soprano, this serial is presented largely first person, but additional perspective is conveyed by the intimate conversations Tony has with his psychotherapist. We see Tony at work, at home, and in therapy. Moments of black comedy intersperse this aggressive, adult drama, with adult language, and extreme violence.', 'James Gandolfini, Lorraine Bracco, Edie Falco', 9.2, NULL, '2021-07-29 16:27:31', '2021-09-10 06:37:13', 'series', NULL, 1),
(199, 'tt2861424', 'Rick and Morty', NULL, '23 min', '2013-12-02', 'Animation, Adventure, Comedy', 'https://m.media-amazon.com/images/M/MV5BZjRjOTFkOTktZWUzMi00YzMyLThkMmYtMjEwNmQyNzliYTNmXkEyXkFqcGdeQXVyNzQ1ODk3MTQ@._V1_SX300.jpg', 'tt2861424.jpg', 'An animated series on adult-swim about the infinite adventures of Rick, a genius alcoholic and careless scientist, with his grandson Morty, a 14 year-old anxious boy who is not so smart. Together, they explore the infinite universes; causing mayhem and running into trouble.', 'Justin Roiland, Chris Parnell, Spencer Grammer', 9.2, NULL, '2021-07-29 16:27:43', '2021-09-10 06:37:16', 'series', NULL, 1),
(200, 'tt0071075', 'The World at War', NULL, '52 min', '1973-09-14', 'Documentary, History, War', 'https://m.media-amazon.com/images/M/MV5BYzExN2NhZDctOWEzMy00NzYwLTg3MDktNjYyNTQyOWY4MGYwXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg', 'tt0071075.jpg', 'A multi-volumed documentary mini-series, \"The World at War\" covers the entire history of World War II from the causes of the 1920s to the aftermath of the Cold War in the 1950s. Emphasis is also placed on several inside story episodes, where events are covered which occurred inside Germany and Japan such as resistance to Hitler, life in general under a dictatorial regime, and particular emphasis is focused on the Jewish Holocaust.', 'Laurence Olivier, Anthony Eden, Averell Harriman', 9.2, NULL, '2021-07-29 16:27:54', '2021-09-10 06:37:18', 'series', NULL, 1),
(201, 'tt8420184', 'The Last Dance', NULL, '491 min', '2020-04-19', 'Documentary, Biography, History', 'https://m.media-amazon.com/images/M/MV5BY2U1ZTU4OWItNGU2MC00MTg1LTk4NzUtYTk3ODhjYjI0MzlmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg', 'tt8420184.jpg', 'Charting the rise of the 1990\'s Chicago Bulls, led by Michael Jordan, one of the most notable dynasties in sports history.', 'Phil Jackson, Michael Jordan, David Aldridge', 9.1, NULL, '2021-07-29 16:28:06', '2021-09-10 06:37:20', 'series', NULL, 1),
(202, 'tt5442430', 'Life', NULL, '104 min', '2017-03-24', 'Horror, Sci-Fi, Thriller', 'https://m.media-amazon.com/images/M/MV5BMzAwMmQxNTctYjVmYi00MDdlLWEzMWUtOTE5NTRiNDhhNjI2L2ltYWdlXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg', 'tt5442430.jpg', 'Six astronauts aboard the space station study a sample collected from Mars that could provide evidence for extraterrestrial life on the Red Planet. The crew determines that the sample contains a large, single-celled organism - the first example of life beyond Earth. But..things aren\'t always what they seem. As the crew begins to conduct research, and their methods end up having unintended consequences, the life form proves more intelligent than anyone ever expected.', 'Jake Gyllenhaal, Rebecca Ferguson, Ryan Reynolds', 6.6, NULL, '2021-07-29 16:28:18', '2021-09-10 06:37:23', 'movie', NULL, 1),
(203, 'tt1355642', 'Hagane no renkinjutsushi', NULL, '24 min', '2009-04-09', 'Animation, Action, Adventure', 'https://m.media-amazon.com/images/M/MV5BZmEzN2YzOTItMDI5MS00MGU4LWI1NWQtOTg5ZThhNGQwYTEzXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg', 'tt1355642.jpg', 'Two brothers lose their mother to an incurable disease. With the power of \"alchemy\", they use taboo knowledge to resurrect her. The process fails, and as a toll for using this type of alchemy, the older brother, Edward Elric loses his left leg while the younger brother, Alphonse Elric loses his entire body. To save his brother, Edward sacrifices his right arm and is able to affix his brother\'s soul to a suit of armor. With the help of a family friend, Edward receives metal limbs - \"automail\" - to replace his lost ones. With that, Edward vows to search for the Philosopher\'s Stone to return the brothers to their original bodies, even if it means becoming a \"State Alchemist\", one who uses his/her alchemy for the military.', 'Kent Williams, Iemasa Kayumi, Vic Mignogna', 9.1, NULL, '2021-07-29 16:28:30', '2021-09-10 06:37:25', 'series', NULL, 1),
(204, 'tt1475582', 'Sherlock', NULL, '88 min', '2010-10-24', 'Crime, Drama, Mystery', 'https://m.media-amazon.com/images/M/MV5BMWY3NTljMjEtYzRiMi00NWM2LTkzNjItZTVmZjE0MTdjMjJhL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTQ4NTc5OTU@._V1_SX300.jpg', 'tt1475582.jpg', 'In this modernized version of the Conan Doyle characters, using his detective plots, Sherlock Holmes lives in early 21st century London and acts more cocky towards Scotland Yard\'s detective inspector Lestrade because he\'s actually less confident. Doctor Watson is now a fairly young veteran of the Afghan war, less adoring and more active.', 'Benedict Cumberbatch, Martin Freeman, Una Stubbs', 9.1, NULL, '2021-07-29 16:28:40', '2021-09-10 06:37:27', 'series', NULL, 1),
(205, 'tt1877514', 'The Vietnam War', NULL, '990 min', '2017-09-17', 'Documentary, History, War', 'https://m.media-amazon.com/images/M/MV5BYWQ4ZGFhYmUtNDVhNC00N2VkLWIzYTQtOTk5ZTI1NWU2YjNlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg', 'tt1877514.jpg', 'Ken Burns and Lynn Novick\'s ten-part, 18-hour documentary series, THE VIETNAM WAR, tells the epic story of one of the most consequential, divisive, and controversial events in American history as it has never before been told on film. Visceral and immersive, the series explores the human dimensions of the war through revelatory testimony of nearly 80 witnesses from all sides-Americans who fought in the war and others who opposed it, as well as combatants and civilians from North and South Vietnam. Ten years in the making, the series includes rarely seen and digitally re-mastered archival footage from sources around the globe, photographs taken by some of the most celebrated photojournalists of the 20th Century, historic television broadcasts, evocative home movies, and secret audio recordings from inside the Kennedy, Johnson, and Nixon administrations. THE VIETNAM WAR features more than 100 iconic musical recordings from greatest artists of the era and haunting original music from Trent Reznor and Atticus Ross as well as the Silk Road Ensemble featuring Yo-Yo Ma.', 'Peter Coyote, Huy Duc, James Willbanks', 9.1, NULL, '2021-07-29 16:28:59', '2021-09-10 06:37:30', 'series', NULL, 1),
(229, NULL, NULL, '[zigmacmov-229]-[zigfetched]-BohemianRhapsody2018', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F:/sym', '2021-09-12 22:33:56', '2021-09-12 22:37:13', NULL, NULL, 0),
(230, NULL, NULL, '[zigmacmov-230]-[zigfetched]-The Tomorrow War 2021', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F:/sym', '2021-09-12 22:33:56', '2021-09-12 22:37:06', NULL, NULL, 0);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
